import streamlit as st
import pandas as pd

# 1. LOAD THE GRADED DATA
# This file is generated by your process_voter_data.py script
try:
    df = pd.read_csv('voter_grades_app.csv')
except FileNotFoundError:
    st.error("Data file not found. Please ensure 'voter_grades_app.csv' is in your GitHub folder.")
    st.stop()

st.set_page_config(page_title="Conformalytics | Super Voter", page_icon="🛡️")

# --- STEP 1: DEFINE THE DISPLAY FUNCTION FIRST ---
# Defining this at the top prevents the "NameError"
def show_grades(v):
    st.divider()
    
    # Clean up the suffix display so it doesn't show "nan"
    suffix = str(v['NSUFFIX']) if pd.notnull(v['NSUFFIX']) and str(v['NSUFFIX']).lower() != 'nan' else ""
    full_name = f"{v['FNAME']} {v['LNAME']} {suffix}".strip()
    
    st.subheader(f"Scorecard for {full_name}")
    
    # Participation Metrics
    g1, g2, g3 = st.columns(3)
    
    # Use st.metric for that professional dashboard look
    g1.metric("General Elections", v['General_Grade'])
    g2.metric("Primary Elections", v['Primary_Grade'])
    g3.metric("Special Elections", v['Special_Grade'])
    
    # Methodology Footnote
    st.caption(f"**Methodology:** Grades are eligibility-adjusted based on Ward {v['WRD_STR']} and your District registration year ({int(v['RegYear'])}).")

# --- STEP 2: BRANDING & UI ---
# Place your DC Crest image in your GitHub repo and update the name here
# st.image("dc_superman_crest.png", width=150) 

st.title("🛡️ Super Voter Identifier")
st.markdown("### Are You A Supervoter?")

# --- STEP 3: SEARCH LOGIC ---
with st.container():
    c1, c2 = st.columns(2)
    lname_input = c1.text_input("Last Name").upper().strip()
    snum_input = c2.text_input("Street Number (Numeric Part of Address)").strip()

if lname_input and snum_input:
    # Filter data based on Step 1 of the "Two-Step Search"
    results = df[(df['LNAME'] == lname_input) & (df['StreetNum'].astype(str) == snum_input)]
    
    if results.empty:
        st.error("No records found at this address. Please check your spelling.")
    
    elif len(results) > 1:
        # Step 2: Disambiguation for Keith/Kim or Jr/Sr
        st.info("Multiple voters found at this address. Please select your record:")
        
        # Create a clean label for the dropdown
        results = results.copy()
        results['Suffix_Clean'] = results['NSUFFIX'].apply(lambda x: str(x) if pd.notnull(x) and str(x).lower() != 'nan' else "")
        results['Label'] = results['FNAME'] + " " + results['Suffix_Clean'] + " (Reg: " + results['RegYear'].astype(str) + ")"
        
        choice = st.selectbox("Select your name:", results['Label'])
        
        # Match the selection back to the data
        voter = results[results['Label'] == choice].iloc[0]
        show_grades(voter)

    with st.expander("Methodology, Privacy & Legal Disclaimer"):
    st.markdown("""
    **Methodology**
    Our grades are 'Eligibility-Adjusted.' We only count elections that occurred after your DC registration date and within your specific Ward...
    
    **Privacy**
    We do not store your search data. This tool uses public DCBOE records...
    
    **Disclaimer**
    For informational purposes only. Not an official government record...
    """)
    
    else:
        # Immediate result if only one person matches
        voter = results.iloc[0]
        show_grades(voter)
