import streamlit as st
import pandas as pd

# 1. LOAD THE DATA
# Ensure 'voter_grades_app.csv' (generated by the data engine) is in your GitHub repo
try:
    df = pd.read_csv('voter_grades_app.csv')
except FileNotFoundError:
    st.error("Data file not found. Please ensure 'voter_grades_app.csv' is in your GitHub repository.")
    st.stop()

st.set_page_config(page_title="Conformalytics | Super Voter", page_icon="🛡️")

# --- STEP 1: DEFINE DISPLAY FUNCTIONS ---

def show_grades(v):
    st.divider()
    
    # Handle "nan" suffix and clean name display
    suffix = str(v['NSUFFIX']) if pd.notnull(v['NSUFFIX']) and str(v['NSUFFIX']).lower() != 'nan' else ""
    full_name = f"{v['FNAME']} {v['LNAME']} {suffix}".strip()
    
    st.subheader(f"Scorecard for {full_name}")
    
    # Participation Metrics
    g1, g2, g3 = st.columns(3)
    
    g1.metric("General", v['General_Grade'])
    g2.metric("Primary", v['Primary_Grade'])
    g3.metric("Specials", v['Special_Grade'])
    
    st.caption(f"**Methodology:** Grades are eligibility-adjusted based on Ward {v['WRD_STR']} and your District registration year ({int(v['RegYear'])}).")

def show_disclaimers():
    with st.expander("Methodology, Privacy & Legal Disclaimer"):
        st.markdown("""
        ### **Methodology**
        Grades are calculated using an **Eligibility-Adjusted Participation Model**. Unlike standard voter scores that penalize residents for missing elections they were not eligible for, our system normalizes participation based on:
        * **Registration Date:** We only count elections that occurred *after* you registered in the District.
        * **Ward-Specific Eligibility:** For Special Elections, you are only graded on contests where your specific Ward was eligible to participate.
        * **The Scale:** Participation percentages are converted to a standard A–F academic scale.

        ### **Privacy & Data Security**
        At Conformalytics, we prioritize data integrity and user privacy:
        * **No Data Retention:** We do not store, track, or save the names or addresses entered into this tool. Your search is processed in real-time and cleared immediately upon closing the session.
        * **Public Records:** This tool utilizes the public voter file provided by the District of Columbia Board of Elections (DCBOE). We do not display sensitive Personally Identifiable Information (PII) such as birth dates or social security numbers.
        * **Encryption:** This application is served over an encrypted (SSL) connection to ensure your search remains secure.

        ### **Legal Disclaimer**
        This tool is provided for **informational and educational purposes only**. While Conformalytics strives for accuracy, the data is derived from third-party public records which may contain clerical errors or update lags. 
        
        This tool does not constitute an official government record or an official statement of your voting status. To verify your official registration or voting history, please visit the [DC Board of Elections website](https://dcboe.org). Conformalytics is an independent consultancy and is not affiliated with, or endorsed by, any government agency.
        """)

# --- STEP 2: BRANDING & UI ---

# Placeholder for the Superman-style DC Crest
# st.image("dc_superman_crest.png", width=120) 

st.title("🛡️ Super Voter Identifier")
st.markdown("### Are You A Supervoter?")

# --- STEP 3: TWO-STEP SEARCH LOGIC ---

with st.container():
    c1, c2 = st.columns(2)
    lname_input = c1.text_input("Last Name").upper().strip()
    snum_input = c2.text_input("Street Number").strip()

if lname_input and snum_input:
    # Initial Search: Filter by Last Name and Street Number
    results = df[(df['LNAME'] == lname_input) & (df['StreetNum'].astype(str) == snum_input)]
    
    if results.empty:
        st.error("No records found at this address. Please check your spelling and street number.")
    
    elif len(results) > 1:
        # Step 2: Disambiguation (Collision Handling)
        st.info("Multiple voters found at this address. Please select your specific record:")
        
        # Create a clean label for the dropdown to distinguish residents
        results = results.copy()
        results['Suffix_Clean'] = results['NSUFFIX'].apply(lambda x: str(x) if pd.notnull(x) and str(x).lower() != 'nan' else "")
        results['Label'] = results['FNAME'] + " " + results['Suffix_Clean'] + " (Reg: " + results['RegYear'].astype(str) + ")"
        
        choice = st.selectbox("Who are you looking for?", results['Label'])
        
        # Match selection back to data
        voter = results[results['Label'] == choice].iloc[0]
        show_grades(voter)
    
    else:
        # Single result found
        voter = results.iloc[0]
        show_grades(voter)

# --- STEP 4: FOOTER ---
st.write("\n")
show_disclaimers()
